site_name: My Knowledge Base
theme:
  name: material
nav:
  - Home: index.md
  - MQTT: mqtt_protocol.md
  - Git:
      - Scoping: git/git_scoping.md
  - NuGet:
      - Package Generation: nuget/nuget_package_generation.md
plugins:
  - search
  - tags
  - git-revision-date

